name: auto-review-committee-pr
on:
  pull_request:
    types: [review_requested, synchronize]
    branches:
      - develop

env:
  TEAM_NAME: committee
  TOKEN: ${{ secrets.AUTO_REVIEW_KEY }}

jobs:
  review-committee-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Check is author committee member
        env:
          APP_TOKEN: ${{ steps.generate-app-token.outputs.token }}
        run: |
          status_code=$(curl -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ env.TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/orgs/${{github.repository_owner}}/teams/${{env.TEAM_NAME}}/memberships/${{github.actor}} \
            -o /dev/null \
            --write-out "%{http_code}" \
            -sS
          )
          
          echo "status_code: $status_code"
          
          if [ "$status_code" == "200" ]; then
            echo "IS_COMMITTEE_MEMBER=TRUE" >> $GITHUB_ENV
          elif [ "$status_code" == "404" ]; then
            echo "IS_COMMITTEE_MEMBER=FALSE" >> $GITHUB_ENV
          else
            echo "Unexpected status code: $status_code"
            exit 1
          fi

      - name: Review the PR
        if: ${{ env.IS_COMMITTEE_MEMBER == 'TRUE' }}
        env:
          GH_TOKEN: ${{ env.TOKEN }}
        run: |
          gh pr review ${{github.event.number}} \
            --approve \
            --body "Auto-review because committee user commits to develop."
